# Generated by Django 4.2.3 on 2023-08-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
    ]
